name: CI-typescript-plugin

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
    - '*'

jobs:
  install-type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          cd template
          yarn install
          yarn add -D typescript @types/jest @types/react @types/react-native @types/react-test-renderer @types/fbemitter @types/react-redux
      - name: Run type check
        run: |
          cd template
          cp plugins/typescript/template/tsconfig.dev.json plugins/typescript/template/tsconfig.json
          yarn type-check
